import { StyleSheet, Platform } from 'react-native';
import { Color, Fonts } from '../styles/themes';
import {
  normalizeVerticaly,
  normalizeHorizontaly,
} from '../../constants/constants';

export const styles = StyleSheet.create({
  modalBackgroundContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Color.modalColor.blackTranslucent,
  },
  modalContainer: {
    backgroundColor: Color.commonColors.whiteColor,
    width: normalizeHorizontaly(335),
    borderRadius: 6,
  },
  textMultiLineHeight: {
    height: normalizeVerticaly(97),
  },
  textMarginTop: {
    marginTop: normalizeVerticaly(10),
  },
  closeIconContainer: {
    opacity: 1,
    position: 'absolute',
    right: normalizeHorizontaly(12),
    top: normalizeVerticaly(10),
  },
  closeIconCenter: {
    opacity: 1,
    position: 'absolute',
    right: normalizeHorizontaly(12),
    top: normalizeVerticaly(30),
  },
  headingText: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.extraBold,
    fontSize: Fonts.fontSizes.fontSize_16,
    alignSelf: 'center',
    paddingBottom: normalizeVerticaly(20),
    paddingTop: normalizeVerticaly(20),
  },
  lineView: {
    borderBottomColor: Color.modalColor.blackTransparent,
    borderBottomWidth: 1,
    marginLeft: '3.2%',
    marginRight: '3.2%',
  },
  viewTextFields: {
    height: normalizeVerticaly(236),
    paddingHorizontal: normalizeHorizontaly(22),
  },
  modalText: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.medium,
    fontSize: Fonts.fontSizes.fontSize_14,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
    textAlign: 'center',
    margin: '7%',
  },
  buttonContainer: {
    borderRadius: 6,
    paddingTop: normalizeVerticaly(13),
    paddingBottom: normalizeVerticaly(13),
    marginTop: normalizeVerticaly(20),
    marginBottom: normalizeVerticaly(21),
    marginRight: normalizeHorizontaly(26),
    marginLeft: normalizeHorizontaly(26),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Color.action.active,
  },
  horizontalButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-evenly',
    marginTop: normalizeVerticaly(20),
    marginBottom: normalizeVerticaly(21),
    marginHorizontal: normalizeHorizontaly(24),
  },
  horizontalPrimaryButtonStyle: {
    borderRadius: 6,
    paddingVertical: normalizeVerticaly(13),
    paddingHorizontal: normalizeHorizontaly(55),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Color.action.active,
    marginLeft: normalizeHorizontaly(20),
  },
  horizontalSecondaryBtnStyle: {
    color: Color.action.active,
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_16,
    letterSpacing: 0.23,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: normalizeVerticaly(13),
    marginHorizontal: normalizeHorizontaly(35),
  },
  buttonText: {
    color: Color.commonColors.whiteColor,
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_16,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  cancelText: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_14,
    textAlign: 'center',
    textTransform: 'uppercase',
    paddingTop: normalizeVerticaly(13),
    paddingBottom: normalizeVerticaly(25),
  },
  secondaryBtnStyle: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_14,
    alignSelf: 'center',
    marginBottom: normalizeVerticaly(22),
    letterSpacing: 0.23,
  },
  buttonShadow: {
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
  },
  bottomContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flex: 1,
    shadowColor: Color.action.dark200,
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 5,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  messageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerCustomMargin: {
    marginBottom: normalizeVerticaly(60),
  },
  cancelTextStyle: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_16,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: normalizeVerticaly(22),
  },
  buttonContainerStyle: {
    borderRadius: 6,
    marginVertical: normalizeVerticaly(20),
    marginRight: normalizeHorizontaly(26),
    marginLeft: normalizeHorizontaly(26),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Color.action.active,
    height: normalizeVerticaly(46),
  },
  secondaryButtonContainer: {
    marginRight: normalizeHorizontaly(26),
    marginLeft: normalizeHorizontaly(26),
    justifyContent: 'center',
    alignItems: 'center',
    height: normalizeVerticaly(46),
  },
  modalTextStyle: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_16,
    lineHeight: 20,
    textAlign: 'center',
    marginHorizontal: '7%',
    marginVertical: normalizeVerticaly(20),
  },
  headerTextStyle: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.extraBold,
    fontSize: Fonts.fontSizes.fontSize_16,
    alignSelf: 'center',
    lineHeight: 20,
    paddingTop: normalizeVerticaly(30),
    paddingBottom: normalizeVerticaly(28),
  },
  headerTextWrapperStyle: {
    color: Color.action.dark,
    fontFamily: Fonts.fonts.extraBold,
    fontSize: Fonts.fontSizes.fontSize_16,
    textAlign: 'center',
    lineHeight: 20,
    marginHorizontal: normalizeHorizontaly(40),
    paddingTop: normalizeVerticaly(12),
    paddingBottom: normalizeVerticaly(10),
  },
});
