import { Platform, StyleSheet } from 'react-native';
import { Color, Fonts } from '../styles/themes';
import {
  normalizeVerticaly,
  normalizeHorizontaly,
  VIEW_NON_EDITABLE_HEIGHT,
  FORM_TEXT_INPUT_CONTAINER_HEIGHT,
  TEXT_INPUT_CONTAINER_HEIGHT,
} from '../../constants/constants';

export const styles = StyleSheet.create({
  cardContainer: {
    flexDirection: 'row',
    width: '91%',
    marginHorizontal: normalizeHorizontaly(18),
    paddingHorizontal: normalizeHorizontaly(9),
    marginVertical: normalizeVerticaly(7.5),
    borderRadius: 5,
    backgroundColor: Color.action.default,
    borderWidth: 1,
    borderColor: Color.action.cardBorderColor,
    shadowColor: Color.action.cardBorderColor,
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 5,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  cardTextView: {
    flex: 0.93,
  },
  cardArrowView: {
    flex: 0.07,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewModalHeight: {
    height: normalizeVerticaly(396),
  },
  textHeader: {
    fontFamily: Fonts.fonts.bold,
    fontSize: Fonts.fontSizes.fontSize_18,
    color: Color.textFieldTextColors.active,
    lineHeight: 22,
    paddingHorizontal: normalizeVerticaly(8),
    marginTop: normalizeVerticaly(15),
    marginBottom: normalizeVerticaly(7),
  },
  textSubTitle: {
    fontFamily: Fonts.fonts.medium,
    fontSize: Fonts.fontSizes.fontSize_14,
    color: Color.action.dark,
    letterSpacing: 0,
    lineHeight: 20,
    textAlign: 'left',
    paddingHorizontal: normalizeVerticaly(8),
  },
  textBottom: {
    paddingHorizontal: normalizeVerticaly(8),
    marginTop: normalizeVerticaly(5),
    marginBottom: normalizeVerticaly(10),
    lineHeight: 18,
    fontSize: Fonts.fontSizes.fontSize_14,
    fontFamily: Fonts.fonts.medium,
    color: Color.action.dark300,
  },
  viewButton: {
    backgroundColor: Color.action.default,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    height: normalizeVerticaly(80),
    bottom: 0,
    left: 0,
    right: 0,
  },
  buttonStyle: {
    width: '88%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewNonEditableStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: VIEW_NON_EDITABLE_HEIGHT,
    paddingHorizontal: normalizeHorizontaly(18),
    borderRadius: 5,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Color.borderColors.nonEditableViewBorder,
  },
  viewEditableStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: VIEW_NON_EDITABLE_HEIGHT,
    backgroundColor: Color.action.default,
    paddingHorizontal: normalizeHorizontaly(18),
    borderRadius: 5,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Color.borderColors.containerBorder,
  },
  textTitleNonEditableStyle: {
    alignSelf: 'center',
    fontSize: Fonts.fontSizes.fontSize_16,
    lineHeight: 24,
    fontFamily: Fonts.fonts.medium,
    color: Color.action.dark,
  },
  textTitleEditableStyle: {
    alignSelf: 'center',
    fontSize: Fonts.fontSizes.fontSize_16,
    lineHeight: 24,
    fontFamily: Fonts.fonts.medium,
    color: Color.action.secondary.pressed,
  },
  textValueNonEditableStyle: {
    alignSelf: 'center',
    fontSize: Fonts.fontSizes.fontSize_16,
    lineHeight: 20,
    fontFamily: Fonts.fonts.bold,
    color: Color.action.dark400,
  },
  textValueEditableStyle: {
    alignSelf: 'center',
    fontSize: Fonts.fontSizes.fontSize_16,
    lineHeight: 20,
    fontFamily: Fonts.fonts.bold,
    color: Color.action.active,
  },
  scanComponentRightIconContainer: {
    position: 'absolute',
    right: 0,
    bottom: 8,
    justifyContent: 'center',
  },
  listContainerNoButtonPadding: {
    paddingBottom: 0,
  },
  textInputContainer: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    height: FORM_TEXT_INPUT_CONTAINER_HEIGHT,
    marginVertical: '3%',
    lineHeight: 21,
    borderRadius: 5,
    fontFamily: Fonts.fonts.medium,
    fontSize: Fonts.fontSizes.fontSize_18,
    backgroundColor: Color.action.default,
    borderWidth: 1,
    borderColor: Color.action.cardBorderColor,
    shadowColor: Color.action.cardBorderColor,
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 5,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  selectionTextInputContainer: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    height: TEXT_INPUT_CONTAINER_HEIGHT,
    marginVertical: '3%',
    lineHeight: 21,
    borderRadius: 5,
    fontFamily: Fonts.fonts.medium,
    fontSize: Fonts.fontSizes.fontSize_18,
    backgroundColor: Color.action.default,
    borderWidth: 1,
    borderColor: Color.action.cardBorderColor,
    shadowColor: Color.action.cardBorderColor,
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 1,
        shadowRadius: 5,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  editableTextStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Color.action.default,
    paddingHorizontal: normalizeHorizontaly(18),
    borderRadius: 5,
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Color.borderColors.containerBorder,
  },
});
