export default {
    HOME: "home",
    COMP_ONE:"CompOne",
    COMP_TWO:"CompTwo",
    COMP_THREE:"CompThree",
    COMP_FOUR: 'CompFour',
    COMP_FIVE: 'CompFive',
    COMP_SIX: 'CompSix',
    COMP_SEVEN: 'CompSeven',
    COMP_EIGHT: 'CompEight',
    COMP_NINE: 'CompNine',
    COMP_TEN: 'CompTen',
    COMP_ELEVEN: 'CompEleven',
    COMP_TWELVE: 'CompTwelve',
    COMP_THIRTEEN: 'CompThirteen',
    COMP_FOURTEEN: 'CompFourteen',
    COMP_FIFTEEN: 'CompFifteen',
    COMP_SIXTEEN: 'CompSixteen',
    COMP_SEVENTEEN: 'CompSeventeen',
    COMP_EIGHTEEN: 'CompEighteen',
    COMP_NINETEEN: 'CompNineteen'
}