export default {
    HOME: "home",
    CHAT_CARD:"ChatCard",
    CUSTOM_BUTTON:"CustomButton",
    CARD_IMAGE:"CardImage",
    POST_CARD: 'PostCard',
    SHADOW_CARD: 'ShadowCard',
    DROP_DOWN: 'DropDown',
    LOADING: 'Loading',
    Modal_Text: 'ModalText',
    IMAGE_MODAL: 'ImageModal',
    MODAL_INPUT: 'ModalInput',
    CUSTOM_DIALOG: 'CustomDialog',
    CHECK_BOX: 'CheckBox',
    ACTION_SHEET: 'ActionSheet',
    SWITCH: 'Switch',
    ALERT_DIALOG: 'AlertDialog',
    TOOLTIP: 'ToolTip',
    ROWS: 'Rows',
    PICKER: 'Picker',
    PICK_DOCUMENT: 'Document',
    DOWNLOAD_PDF: 'downloadPdf',
    TEXTFIELD: 'TextField',
    TOAST: 'Toast',
    RADIOBUTTONGROUP: 'RadioButtonGroup',
    SCROLL_INDICATOR: 'ScrollIndicator',
    DATE_PICKER: 'DatePicker',
    LINECHART: 'LineChart',
    LANGUAGE: 'Language',
}